// Mocks generated by Mockito 5.0.15 from annotations
// in trancentum_web_app/test/calculate_percentage_of_expeditions_per_status_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:trancentum_web_app/services/expeditions.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Expeditions].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpeditions extends _i1.Mock implements _i2.Expeditions {
  MockExpeditions() {
    _i1.throwOnMissingStub(this);
  }
}
